### ISSUE TITLE
Debugger content disappears after switching context

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#2896]
1. with Firefox Nightly 55.0a1 (2017-05-14) (64-bit)
2. Go to mozilla.org
3. Activate responsive design mode
4. Select a mobile device for example iPhone 6S
5. Enter https://m.fr.aliexpress.com/myaccount/wishlist/detail.htm
6. on Email Address field, do "Inspect Element"
7. The inspector pops up
8. Click on the event and follow through to open the debugger
9. Debugger pops up
10. Go back to the inspector
11. Go back to the debugger

Actual:
The window is empty

You need to close the debugger and reopen to see again the code.

**Comment by jasonLaster** [comment]
Thanks @karlcow we've fixed similar bugs recently. I'll look into it soon :)

**Comment by juliandescottes** [comment]
From what I experienced, the code vanishes also for the simple STRs below:
1. stop on a breakpoint
2. switch to any other tool
3. switch back to debugger

I think I tried locally with the latest master from debugger and I still get the issue.

**Comment by juliandescottes** [comment]
I'm pretty sure this will actually have to be fixed in mozilla central, since we use a different version of the editor component when we are embedded in Firefox. 

I attached a patch to https://bugzilla.mozilla.org/show_bug.cgi?id=1365059 that fixes the issue for me

**Comment by juliandescottes** [comment]
This should be verified once https://bugzilla.mozilla.org/show_bug.cgi?id=1365314 is integrated in Nightly

**Comment by juliandescottes** [comment]
@karlcow the fix in mozilla-central has been released in the latest Nightly, can you check if it's fixed for you?

**Comment by karlcow** [comment]
🎉 ☀️ Thanks a lot. Fixed.
